using System.Numerics;
using Content.Client.CMU14.UI;
using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.Chemistry.Research;

[GenerateTypedNameReferences]
public sealed partial class ChemSimulatorWindow : DefaultWindow
{
    public static readonly Color ModeColor = Color.FromHex("#d3bd9a");
    public static readonly Color ActionColor = Color.FromHex("#d6d6d6");
    public static readonly Color OverrideActiveColor = Color.FromHex("#b08080");
    public static readonly Color CreditsGood = Color.FromHex("#9dc79f");
    public static readonly Color CreditsAverage = Color.FromHex("#d3bd9a");
    public static readonly Color CreditsBad = Color.FromHex("#b08080");

    private static readonly Color HeaderColor = Color.FromHex("#12141A");
    public static readonly Color GreenColor = Color.FromHex("#4CAF50");
    public static readonly Color TanColor = Color.FromHex("#ffb950");
    public static readonly Color OrangeColor = Color.FromHex("#C99A29");
    public static readonly Color RedColor = Color.FromHex("#8B2020");
    public static readonly Color DarkRowColor = Color.FromHex("#22262F");

    public static readonly Color PropertyPositiveColor = Color.FromHex("#9dc79f");
    public static readonly Color PropertyNegativeColor = Color.FromHex("#d19a9a");

    public ChemSimulatorWindow()
    {
        RobustXamlLoader.Load(this);

        var resourceCache = IoCManager.Resolve<IResourceCache>();
        CreditsLabel.FontOverride = resourceCache.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", 12);

        foreach (var header in new[]
                 {
                     StatusHeader, ModeHeader, ActionsHeader,
                     TargetHeader, ReferenceHeader, RecipePickerHeader,
                 })
        {
            header.PanelOverride = new StyleBoxFlat { BackgroundColor = HeaderColor };
        }

        foreach (var modeButton in new[] { AmplifyButton, SuppressButton, RelateButton, AddButton })
        {
            modeButton.ToggleMode = true;
            Colored(modeButton, ModeColor);
        }

        foreach (var actionButton in new[] { SimulateButton, EjectTargetButton, EjectReferenceButton, FinalizeButton })
        {
            Colored(actionButton, ActionColor);
        }

        OverrideButton.ToggleMode = true;
        Colored(OverrideButton, ActionColor);

        FinalizeButton.Text = Loc.GetString("research-sim-ui-finalize");

        Icon(resourceCache, SimulateButton, CMUIcons.Radiation, Loc.GetString("research-sim-ui-simulate"));
        Icon(resourceCache, EjectTargetButton, CMUIcons.Eject, Loc.GetString("research-sim-ui-eject-targ"));
        Icon(resourceCache, EjectReferenceButton, CMUIcons.Eject, Loc.GetString("research-sim-ui-eject-ref"));
        Icon(resourceCache, AmplifyButton, CMUIcons.SquarePlus, Loc.GetString("research-sim-ui-amplify"));
        Icon(resourceCache, SuppressButton, CMUIcons.SquareMinus, Loc.GetString("research-sim-ui-suppress"));
        Icon(resourceCache, AddButton, CMUIcons.ArrowRightLong, Loc.GetString("research-sim-ui-add"));
        Icon(resourceCache, RelateButton, CMUIcons.ArrowsRotate, Loc.GetString("research-sim-ui-relate"));
        Icon(resourceCache, OverrideButton, CMUIcons.Server, Loc.GetString("research-sim-ui-override"));
    }

    public static void Row(PanelContainer panel, Label label, Color color)
    {
        panel.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
        label.FontColorOverride = color == RedColor ? Color.White : Color.Black;
    }

    public static void Row(PanelContainer panel, Label label, string text, Color color)
    {
        label.Text = text;
        Row(panel, label, color);
    }

    public static void Colored(Button button, Color color)
    {
        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = color,
            BorderColor = Color.Black,
            BorderThickness = new Thickness(1),
        };
        button.ModulateSelfOverride = Color.White;
    }

    public static void SetModeButton(Button button, bool selected)
    {
        button.Pressed = selected;
        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = selected ? GreenColor : ModeColor,
            BorderColor = selected ? Color.White : Color.Black,
            BorderThickness = new Thickness(selected ? 2 : 1),
        };
        button.ModulateSelfOverride = Color.White;
    }

    public static void SetRowButton(Button button, Color textColor)
    {
        button.Label.FontColorOverride = button.Disabled || button.Pressed ? Color.White : textColor;
        button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = button.Disabled ? RedColor : button.Pressed ? GreenColor : DarkRowColor,
            BorderColor = button.Pressed ? Color.White : Color.Black,
            BorderThickness = new Thickness(button.Pressed ? 2 : 1),
        };
        button.ModulateSelfOverride = Color.White;
    }

    private static void Icon(IResourceCache resourceCache, Button button, string texturePath, string text)
    {
        button.Text = null;

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalAlignment = HAlignment.Stretch,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(10, 0, 6, 0),
            SeparationOverride = 8,
        };

        var texture = new TextureRect
        {
            Texture = resourceCache.GetTexture(texturePath),
            ModulateSelfOverride = CMUIcons.Idle,
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            SetSize = new Vector2(20, 20),
            VerticalAlignment = VAlignment.Center,
        };
        row.AddChild(texture);

        var label = new Label
        {
            Text = text,
            FontColorOverride = Color.Black,
            VerticalAlignment = VAlignment.Center,
            HorizontalExpand = true,
            ClipText = true,
        };
        row.AddChild(label);

        button.AddChild(row);

        button.OnMouseEntered += _ => texture.ModulateSelfOverride = CMUIcons.Hover;
        button.OnMouseExited += _ => texture.ModulateSelfOverride = CMUIcons.Idle;
    }

    public sealed class SelectButton : Button
    {
        public string Id = string.Empty;
        public Action<string>? OnSelect;

        public SelectButton()
        {
            ToggleMode = true;
            OnPressed += _ => OnSelect?.Invoke(Id);
        }
    }
}
